# ERD (Mermaid)

```mermaid
erDiagram
    MEMBER {
        BIGINT member_id PK
        VARCHAR name
        VARCHAR email
        VARCHAR password
        VARCHAR phone_number
        VARCHAR address
        CHAR gender
        DATE date_of_birth
        DATETIME created_at
        DATETIME updated_at
    }
